version: '3.8'

services:
  hiring-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: "http://localhost:8080"
    image: hiring-frontend:latest
    ports:
      - "3000:8080"
    restart: unless-stopped