FROM node:20-alpine AS deps

ARG NEXT_PUBLIC_BACKEND_URL

ENV NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL:-https://kireon-backend-510702145393.europe-west4.run.app}
ARG NEXT_PUBLIC_ALLOW_ANONYMOUS=true
ENV NEXT_PUBLIC_ALLOW_ANONYMOUS=$NEXT_PUBLIC_ALLOW_ANONYMOUS
RUN echo "NEXT_PUBLIC_BACKEND_URL is: $NEXT_PUBLIC_BACKEND_URL"

WORKDIR /app

COPY package.json yarn.lock ./

# Create .env file from build argument
RUN echo "NEXT_PUBLIC_BACKEND_URL=$NEXT_PUBLIC_BACKEND_URL" > .env && \
    echo "NEXT_PUBLIC_ALLOW_ANONYMOUS=$NEXT_PUBLIC_ALLOW_ANONYMOUS" >> .env

RUN yarn install --frozen-lockfile

FROM node:20-alpine AS builder

ARG NEXT_PUBLIC_BACKEND_URL
ARG NEXT_PUBLIC_ALLOW_ANONYMOUS=true
ENV NEXT_PUBLIC_BACKEND_URL=$NEXT_PUBLIC_BACKEND_URL
ENV NEXT_PUBLIC_ALLOW_ANONYMOUS=$NEXT_PUBLIC_ALLOW_ANONYMOUS

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Create .env file from build argument
RUN echo "NEXT_PUBLIC_BACKEND_URL=$NEXT_PUBLIC_BACKEND_URL" > .env && \
    echo "NEXT_PUBLIC_ALLOW_ANONYMOUS=$NEXT_PUBLIC_ALLOW_ANONYMOUS" >> .env

RUN yarn build

FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV PORT=8080
ENV NEXT_PUBLIC_ALLOW_ANONYMOUS=true



COPY --from=builder /app ./

EXPOSE 8080

CMD ["yarn", "start", "-p", "8080"]