
export enum Country {
    EU = "EU",
    BE = "BE",
    BG = "BG",
    DK = "DK",
    DE = "DE",
    EE = "EE",
    FI = "FI",
    FR = "FR",
    GR = "GR",
    IE = "IE",
    IS = "IS",
    IT = "IT",
    HR = "HR",
    LV = "LV",
    LI = "LI",
    LT = "LT",
    LU = "LU",
    MT = "MT",
    NL = "NL",
    UK_XI = "UK-XI",
    NO = "NO",
    AT = "AT",
    PL = "PL",
    PT = "PT",
    RO = "RO",
    SE = "SE",
    CH = "CH",
    SK = "SK",
    SI = "SI",
    ES = "ES",
    CZ = "CZ",
    TR = "TR",
    HU = "HU",
    CY = "CY",
    UK = "UK"
}

export const CountryName: Record<Country, string> = {
    [Country.EU]: "EU-harmonisiert",
    [Country.BE]: "Belgien",
    [Country.BG]: "Bulgarien",
    [Country.DK]: "Dänemark",
    [Country.DE]: "Deutschland",
    [Country.EE]: "Estland",
    [Country.FI]: "Finnland",
    [Country.FR]: "Frankreich",
    [Country.GR]: "Griechenland",
    [Country.IE]: "Irland",
    [Country.IS]: "Island",
    [Country.IT]: "Italien",
    [Country.HR]: "Kroatien",
    [Country.LV]: "Lettland",
    [Country.LI]: "Liechtenstein",
    [Country.LT]: "Litauen",
    [Country.LU]: "Luxemburg",
    [Country.MT]: "Malta",
    [Country.NL]: "Niederlande",
    [Country.UK_XI]: "Nordirland",
    [Country.NO]: "Norwegen",
    [Country.AT]: "Österreich",
    [Country.PL]: "Polen",
    [Country.PT]: "Portugal",
    [Country.RO]: "Rumänien",
    [Country.SE]: "Schweden",
    [Country.CH]: "Schweiz",
    [Country.SK]: "Slowakei",
    [Country.SI]: "Slowenien",
    [Country.ES]: "Spanien",
    [Country.CZ]: "Tschechien",
    [Country.TR]: "Türkei",
    [Country.HU]: "Ungarn",
    [Country.CY]: "Zypern",
    [Country.UK]: "Vereinigtes Königreich"
};

export const MarketsAll: Country[] = [
    Country.EU,
    Country.BE,
    Country.BG,
    Country.DK,
    Country.DE,
    Country.EE,
    Country.FI,
    Country.FR,
    Country.GR,
    Country.IE,
    Country.IS,
    Country.IT,
    Country.HR,
    Country.LV,
    Country.LI,
    Country.LT,
    Country.LU,
    Country.MT,
    Country.NL,
    Country.UK_XI,
    Country.NO,
    Country.AT,
    Country.PL,
    Country.PT,
    Country.RO,
    Country.SE,
    Country.CH,
    Country.SK,
    Country.SI,
    Country.ES,
    Country.CZ,
    Country.TR,
    Country.HU,
    Country.CY,
    Country.UK
];
